<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="Usuarios.aspx.cs" Inherits="EJERCICIO04.Usuarios" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div>

              
     <p>&nbsp;</p>
    </div>
    <div>
        <br />
        <br />
        <asp:GridView runat="server" ID="datagrid" HorizontalAlign="Center"
            CssClass="mydatagrid" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header"
            RowStyle-CssClass="rows" AllowPaging="True" AutoGenerateDeleteButton="True" OnSelectedIndexChanged="datagrid_SelectedIndexChanged" />

        <div class="container text-center">
        Nombre: <asp:TextBox ID="tNombre" class="form-control" runat="server" ></asp:TextBox>
        Correo: <asp:TextBox ID="tCorreoElectronico" class="form-control" runat="server"></asp:TextBox>
        Telefono: <asp:TextBox ID="tTelefono" class="form-control" runat="server"></asp:TextBox>
        UsuariosID: <asp:TextBox ID="tUsuariosID" class="form-control" runat="server"></asp:TextBox>
    </div>

        <br />
        <br />
        <br />

    </div>
    <div class="container text-center">

        <asp:Button ID="BtnAgregar" class="btn btn-outline-primary" runat="server" Text="Agregar"  />
        <asp:Button ID="BtnMod" class="btn btn-outline-secondary" runat="server" Text="Modificar" OnClick="BtnMod_Click" />
        <asp:Button ID="BrnConsult" runat="server" class="btn btn-outline-danger" Text="Consultar" />
        <asp:Button ID="BtnBorrar" runat="server" class="btn btn-outline-danger" Text="Borrar"  />

      
    </div>


        
    
</asp:Content>
